language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./run-check.sh"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload"
  on:
    tags: true
env:
  global:
  - secure: PCaPTarF2KmH9xntVmFbUKhXIUKEdjNww+M1xaMWxSYeO85fbkhhhRC6WhN1+RLpofPuimVBBVSvkFTFBEg+Fg4yfGAQUAMwP/aA0G/X1BIyz/5GoDv6EKR/6kTBpuilZqmqdAldab7MM4MvHbyaqkR14WcpqEAptB4JBwA7gTfhTauF++0yxtz98/LRPWvvGFuOIdkcvsvZroOTgsz9Zs+6LZ41aEsJmJ5nThmb++muC6rRNpCq7TIQgnuVPVgzE02sLZvcrQ2+MeERTv5OCWP5WMo+omHMLVZhVkcfuQIed5jMpX4qikc4Yt5bJHE4tO6E6WWRIHJ/LqpWfWSIdoIFccU6diZPqQ/eLu+mqqd2jy3DuggYLyFRZUKaa8hSlSd4t1jUczljX4fs9oNqZculWVIXDiLS6sW6yH+XK0dlvUZjaOFRY8O5AQARF/nmKJS5griW9e+MCUj8dgTYi6yTsVVkA4M4yckj0k2eF361YJ8b6VsRfXd+uhsFE1OyhOjtZmVeUObzi8nBlpBuKcqeP2Q9cWMKGuiXC+M8zMwAjZ1EzsHEimXn/d+7b2IRRUGgVvEMmZ9gLTBYOjxXJr/RlrRCKKRybgeXTUi1PWorzspKpgvN4wqvFnU7bqxP2YGCHB26gDv7DphAWjbQHMZYz1WeQA2IskreDtB97aE=
  - secure: uUcVjWU073yugSAn3Yhg3Nuvo7n9L7Hh3flfKeHmVEtpzyiF6IITsyLPK8ppWSSEfj6SXeGb5h7yVrgx66umwqCeToZkEgAC6mQ+0MavW5L5js5P7iVa8aB98zh6DljQbsUFqr7tfyeqnMOqGlkWpmfczp4B5P37czE5haTb+6fmMCDpPxRUV8TyNsJjuLWRgRypKo1wJXZDVn/sGTcBcSC/JvPehLmsg82u+yFVTfS2M1iGhdXYV7R9Zr7htYAjuHgoEYBxsn6fF9zhpnQABOwcPzAmLfHsHVBhYPiO43ZXWyQr27AFyL6zTnxMfRTDcj/oocvMX9I81O/C/sjDt4reSWwWvDVtc6iE/4n5nvyqiy7JVbJbXH4wVtjey5jqmxCfToQtewvTspdqf6t5cvocLAh7mwieq3O5yFmaP/F/vfCfClzqIDQ5KMbWnmTegI/lROnybbxWvovEZ/sq38uLrhj/Ll3f3eGLHS/QIJYrVfuGdb/GlcIR5cVfC8YCvExUL5rr2Ms0ScU+W1xPd+4TvAtclYywNh533jilyx7eamYuaFZqf78DC5929mjz86tPwibeIE+tOioxYY+wzPm60piPbWXum58DNEe7R4AbVq0Y9QiUgjGK9BIambDQEsj1LBbThK5dwTi2I1FC85OU68MixQ0GyKn7lHaoqfA=
