language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./run-check.sh"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload --debug"
  on:
    tags: true
env:
  global:
  - secure: BlLrnCv5eC0K5Las66GQtK+XYAd58qf8CpUYxbyvknOaoiwLNIzxQqBq0w7PeAgJ0nAJ0tHpKzy3Uu5jT9pRSSzlgC7rpplJEGqYpIETIIPij3bYaqhJFBF+dK9QnnqjXbcSB2mWO6jQ6jl+ma52gNqe/6+qXzH0PwfBE0WrSjJ6hhrnP1lEXNLYChQ/k7I3yFIYnChoYWk38ZmU9x/gwjxDjh6TyuA8DkRPQ1H4/PetSGd3qfU8jm33sFKas53xI9m3rMLy88ggoY2Huo9Bc32iBAeVr8+xpXb2qqxC2un5BWBsbLkh9d8DDmPf8PD62bedJ6c5E+33qJkpBYIOg2TeTx5QSA6pSPUhiFA+rqpElXVhdl3q8zRuJg9YMBTiSs6cxv54rsrPUip4n901PwH6Ght2C+OUJumR4FiwW9mUaMJuEEZcj/b6BYitfKeOX7DUAqc0RP6qlo7h/VqMKuXke6MeJsNXESdewyI8pjv4Lynj/V4d8Cza1d8DYLPBvc8UTwk66Z+CqkSavs6PBj1Wa5Harl0FFrNGMTAP4FnOof+v3CILPUjhlwWZ2eQiE+4O7G9kJ24msLE/y/pOsjdPNvA3ALkRQQMMRsMqFKYbb1xMerxAz5dbxXVXQVwa9gbKfMmJcQQjwR2F6jVVq5D6q1o6SpX5oT2WTjCAYwA=
  - secure: NYuHNZRYyFtCTEvYvCiBkFi4s95UwSbK12u7M8nDg6DIzEnCukt5dPtwDeSv4csu8WTs+W/y6mAvscmij3+E4tTNYzCJaEhCudbZlDsDcM6/3uV5sHrdICD1r+qN5XnfruDMos4v0AQu5o8bvy6rdPkecJRw7opxSVvIzTR4tBCpM8iv6Lq7T0lU5OIccV8JXF82wk03twJnmC8wE9rXT0hjfnLZRafNGzXvFHooztlaUhl7eJifTdvqGYFL1aOP2rZr1wXMOEAmpsi2jc1F7ST6afVgWItIxkxyMOhz5kYbrjovGek67p8dH6zsM7gS8l5TuJAbfJ2GkJ4oj39Pd1m3iT0sTHlzceVdjRKTu7yU24abGfcChZEWuA05Lw1MITliSJYnvIQOfybpWkWLfQXJfZmTRfqraDHBXX4SYSA8htbKC2+P43EWvprVJFx4KQfegTvYmUqTmEG48CodJ0GaPHMOPV7vmxHjmOhOHOBuckQdw+APUNh0GIi7wWDxjWP3Tvkgu6Q4HAn6rjrqq1qjigwbqcI8PoLnMbfw6HVP+dTMDxeRGEgwxRzxfy7NcvCjwbVUnXljB7Duo+DCmCsSESzN8+BFr6S3KAMxipOSHk7RzfKSeglkZY4XoPtOLbQMulTKFR6peSiO63VfB7hSop4LESDC/rTwcuqYUZM=
