language: groovy
jdk:
- openjdk8
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
script:
- "./run-check.sh"
deploy:
  provider: script
  script: "./gradlew clean assemble bintrayUpload --debug"
  on:
    tags: true
env:
  global:
  - secure: AScuaYk5QAC/GIH9yjG8CpCQn5jYtlmHTMBG9X7gTopBjzlYi7jCTv+0K/4LEYz3R50FidGcDdnteQ52uc0d8yG2+kdrKcRDwY18eDEDm/I4tfy2941nCKIWrGIkEFVGdpfTaT09nYouj/GYm7NSKTah4kFj5QC9HlS8zzbRwicfdwd7up0ZlFKtv0F3gSqvsbJiqPijNhrdsEN6dSxa2b/SRO2d4QX+A4Lf9PUyvjJ3HDx5G6hM8snUfOP5VUYlg0bVay1CMgZFDfMEZ/Soshubx9Vdn86XbMGXCCJ899J/lONNs9/2oAWPIcHaMGx7HLyqlhrTkHhuLAsqsKpnF/+bPWw4Rb4P0h3z8yHPbWWDXmC5J+ZT0FJLGrBej36zubT8LsHj7qEbj4iyoS68m3DK2oR468m4+wRgPfiRGLKxKvNzdTqPW16Fv6glt8rImNY7ughpN3TKLo1sF7Zuob5uUHPCjnf0g5koqFEc2HYCN9wns08UuoEmcvyy34jrppFPygrIXQx70qNZvf5JDidX1mHPkhrmuycEgGyrZY+W7FX/3xtDEfkMeBt/Zht5io3cYs0vcq1beIBw7Yp6Z384U52OmMRh2LLWSuEGD5ZL3N6kBF7TDMlLfIVT71Q08rCVm9w/PQU97G4hfmgrVIPkxdqVHuNV3Y+73Gg1Aqk=
  - secure: vVaxXSXBoJgyr/Z4dSvaoji7GbbNbFAegqBSMEeRuCVLnipnBOTSr4oE6+DDXmNEureTIwAmE1oto9Ws7xj2IVUenwaUA8XOkHAwUUxauCKDKoDOeA+qJbuLrH5IB1XpIon5k5SwyOdvH+NJIKUyolZ5qjzj1TySvXwg/+0zdbpiNlmzsrQxM8YtKlysWJYUYOwQJbu1IC8XgJL39qQjEosTvU5SRc8nS+s1eNqDz5qjf7bqbVK/rlA7D/QkZ1IuiVbxuA4108cIyaZL4z3a/FdDNTaMr+4PDUne8fsN2LpUm6W61XY0lu1Ud+Xp1OK/DMy/49OUWQgAFeyl5ENrVFnLU2WAtqx61q1ShPAgKJZJqAbnhH9g9eR75UlroQC4Dtn6oiPyvBH+4IkGD3vnARbgAxgED212rLfGDF3M/3o9NJ9jGzRGY6iCcxCbF0ZmPntly2JdhMPsCmcpmzP5p78tDlVu3plHzeFTVn33hUS/9cw1btKnEqrHbk5cv/JORX0MZXxUjljPNADekMn0Sz7blB5lcv2QLwBcvi12JHgIbCmigvW9Pof1SCzzWkLUzZ/nOCEjAK83W6jOoBBFs41SNYV4v/iyptYyZ+8X4VYE3Ww83sWmJUbRYtZ/yxtR+rTHueJOftCV4PpU3wKSODXaNmjdeyiN/BOi3aknECw=
