on: push
name: Build and Test
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build
      uses: MrRamych/gradle-actions@1.0
      with:
        args: startDb createTestDb check assemble
